services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    expose:
      - "3306"
    env_file:
      - .env
    volumes:
      - mariadb-volume:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    expose:
      - '9000'
    env_file:
      - .env
    volumes:
      - wordpress-volume:/var/www/html
    networks:
      - inception
    restart: unless-stopped

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    ports:
      - '443:443'
    env_file:
      - .env
    volumes:
      - wordpress-volume:/var/www/html
    networks:
      - inception
    restart: unless-stopped

volumes:
  mariadb-volume:
    name: mariadb-volume
    driver: local
    driver_opts:
      type: none
      device: /home/yonyoo/data/db
      o: bind
  wordpress-volume:
    name: wordpress-volume
    driver: local
    driver_opts:
      type: none
      device: /home/yonyoo/data/wp
      o: bind

networks:
  inception:
    driver: bridge
