services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:yonyoo
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:yonyoo
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - inception
    depends_on:
      - mariadb
    ports:
      - "9000:9000"

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:yonyoo
    restart: unless-stopped
    hostname: localhost
    volumes:
      - wp:/var/www/html/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    ports:
      - "443:443"

volumes:
  db:
    name: db
    driver: local
    driver_opts:
      device: /home/yong/data/db
      o: bind
      type: none
  wp:
    name: wp
    driver: local
    driver_opts:
      device: /home/yong/data/wp
      o: bind
      type: none

networks:
  inception:
    name: inception
